### ISSUE TITLE
App doesn't change after UPDATE_INSTALLED and restart on Android with {N} Angular

### ISSUE THREAD

**Issue by sebawita** [EddyVerbruggen/nativescript-code-push#2]
`nativescript-code-push` works really well with {N} Core Android/iOS and {N} Angular iOS, however it doesn't seem to work with {N} Angular with Android.

The app indicates triggers events with `SyncStatus.UPDATE_INSTALLED`, however when I restart the app the expected changes are not there. `CodePush.sync` returns `SyncStatus.UP_TO_DATE`.

**Comment by EddyVerbruggen** [comment]
For anyone interested what the steps are, here's a super boring video of the entire process: https://www.youtube.com/watch?v=Jl7PYoqO7vY

**Comment by sebawita** [comment]
My mistake was to deploy the app to my Android device with `tns run android`. It turns out that livesync is getting in the way.

Using: `tns run android --no-watch` works :)

**Comment by EddyVerbruggen** [comment]
I'll add a clearer warning to the readme , thanks!
