### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bladerik** [EddyVerbruggen/nativescript-code-push#7]
Hi, i'm trying to register to codepush with a command nativescript-code-push register

but i see this error
![TypeError: Cannot read property 'length' of null](https://cl.ly/ce3244620682/Sni%2525CC%252581mka%252520obrazovky%2525202019-05-24%252520o%2525209.48.25.png)

**Comment by xlcs0110** [comment]
you can change a browser to open it.Safari is works good for me.

**Comment by bladerik** [comment]
Hi, it was not forking for me either in safari. So i installed firefox and register successfully, with some issues, after registration i saw the error again but i was able to get the token :) so closing now... thanks
