### ISSUE TITLE
Failed to open browser

### ISSUE THREAD

**Issue by max-pro** [EddyVerbruggen/nativescript-code-push#8]
I try using nativescript-code-push register cmd it shows register in a browser. But failed to open the browser. So kindly help me to find url so i can directly enter in a browser

**Comment by EddyVerbruggen** [comment]
Hmm, any idea why opening the browser would fail? Perhaps you can tell me something about your machine?
Also note that we may rebrand this service shortly (new name and commands), but I think if you start playing with it now it will keep on working.

**Comment by EddyVerbruggen** [comment]
Note that I've just pushed a change that will implement what you asked: log the url so you may paste it in a browser. Closing, but still curious about your findings.
