### ISSUE TITLE
Re: nativescript-code-push release <codepush-android-appname> android 

### ISSUE THREAD

**Issue by max-pro** [EddyVerbruggen/nativescript-code-push#9]
After try to release app using code-push getting an error.

[Error]  Unable to find or read "E:\project\New folder\demoTesting\app\App_Resources\Android\AndroidManifest.xml".

My new project manifest file path : E:\project\New folder\demoTesting\app\App_Resources\Android\src\AndroidManifest.xml

Old project working fine.

**Comment by EddyVerbruggen** [comment]
What's the old project? Not that 1.0 of this plugin connected to Microsoft's CodePush server whereas 2.0.0 connects to ours. If you have a project you used with 1.0 you should not upgrade to 2.0. Note that we're thinking about renaming this 2.0 project to avoid confusion.

Btw, there's a space in your project path, could that be the cause of the issue?

**Comment by max-pro** [comment]
I'm talking about my old project not codepush old version.Currently i'm using code push version: 2.0
I used nativescript-code-push release demoTesting android --mandatory --targetBinaryVersion *
after that app showing no pending update.

**Comment by EddyVerbruggen** [comment]
Please share a repo. I can’t make sense of this otherwise.

**Comment by max-pro** [comment]
https://drive.google.com/drive/folders/19eMzGzpBNYgBPl9U87xLMvwXt06wh_8R?usp=sharing

**Comment by EddyVerbruggen** [comment]
Would you mind sharing some instructions as well?

**Comment by max-pro** [comment]
Code push not getting an update. Always showing no pending update. I push code using
` nativescript-code-push release demoTesting android --mandatory --targetBinaryVersion *`

nativescript-code-push deployment history demoTesting Staging it shows update version.

**Comment by EddyVerbruggen** [comment]
I don't have your login credentials so I can't check that you have a pending version and neither if the deployment key (`ejGDAjUi1vZoNOyROql1Jqv2M8lkajaGyFMsa`) matches the release channel...

**Comment by max-pro** [comment]
I got deployment key using 
`nativescript-code-push deployment ls demoTesting --displayKeys`
![image](https://user-images.githubusercontent.com/25317893/58749348-c23f2f80-84a2-11e9-89eb-281949e8ce39.png)

**Comment by EddyVerbruggen** [comment]
That's all looking legit. When you run `nativescript-code-push -v`, does it say 1.0.5? If so, can you please send me your login to eddyverbruggen at gmail dot com so I can try running your app?

**Comment by EddyVerbruggen** [comment]
I cloned your repo and ran `tns run ios` from the root. It gave me this prompt (which seems fine):

![Simulator Screen Shot - iPhone 6 - 2019-06-02 at 20 05 14](https://user-images.githubusercontent.com/1426370/58765278-d43bd380-8571-11e9-943e-ebd65bb9e787.png)

**Comment by max-pro** [comment]
Hi,

I tried using tns run android and not showing any popup. Is i'm
doing something wrong?

Thanks & Regards,
Sagar Shinde

**Comment by EddyVerbruggen** [comment]
I don't know. Did you release an update for Android? I only tried it for iOS (see above).

**Comment by tgpetrov** [comment]
I managed to reproduce the same issue. Just created a new app from NativeScript templates (tried with both [blank-ts](https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-blank-ts) and [blank-ng](https://github.com/NativeScript/nativescript-app-templates/tree/master/packages/template-blank-ng). Then built the app for android and tried to push a release. It seems like this plugin is looking for 'AndroidManifest.xml' directly inside `App_Resources/Android`, while the manifest is actually in `App_Resources/Android/src/main`. It is also present in `platforms/android/app/src/main` after app is built.

**Comment by EddyVerbruggen** [comment]
@tgpetrov That would make sense, and also explain why it works for some projects but not for all (because one can configure the app_resources location). I'll investigate further.

**Comment by EddyVerbruggen** [comment]
With plugin version 2.0.2 we drag in CodePush CLI version 1.0.7 which has a few changes to fix the build error on Android @tgpetrov mentioned, and also fixes a similar issue on iOS for projects using dashes (like `blank-ng`).

I hope this also solves the trouble for @max-pro.
